services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      # migrate:
      #   condition: service_completed_successfully
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app/
      
  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    networks:
        - app-network
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
        - app-network
    develop:
      watch:
        - action: rebuild
          path: ./prisma
          target: /app/



networks:
  app-network:
    driver: bridge
